import test from 'node:test';
import assert from 'node:assert/strict';
import { LABORER_PROFILE_FIELDS, buildLaborerSavePayload } from '../lib/labor-profile-write.mjs';
import { SYSTEM } from '../lib/system-constitution.js';
const FORM={full_name:'أحمد',iqama_no:'123',iqama_expiry:'',nationality:'سعودي',labor_class:'worker',trade:'',group_code:'G1',pay_basis:'daily',daily_rate:'150',monthly_salary:'',salary_days:SYSTEM.payroll.monthlyDailyDivisor,piece_rate:'',piece_unit:'م2',deduct_absence:true,phone:'0500000000'};
test('editing never includes contractor_id/project_id',()=>{const p=buildLaborerSavePayload(FORM,{contractorId:'C1',isNew:false});assert.equal('contractor_id'in p,false);assert.equal('project_id'in p,false);assert.equal(p.daily_rate,150);});
test('new laborer stamps contractor_id only for legacy compatibility',()=>assert.equal(buildLaborerSavePayload(FORM,{contractorId:'C1',isNew:true}).contractor_id,'C1'));
test('new laborer without contractor fails loudly',()=>assert.throws(()=>buildLaborerSavePayload(FORM,{isNew:true}),/contractorId is required/));
test('stray loaded-row fields never round-trip',()=>{const p=buildLaborerSavePayload({...FORM,id:'L1',created_at:'x',is_active:true,contractor_id:'OLD',project_id:'P'},{contractorId:'C1',isNew:false});assert.deepEqual(Object.keys(p).sort(),[...LABORER_PROFILE_FIELDS].sort());});
test('empty numeric values become null',()=>{const p=buildLaborerSavePayload(FORM,{contractorId:'C1',isNew:false});assert.equal(p.monthly_salary,null);assert.equal(p.piece_rate,null);});
test('salary_days comes from central constitution',()=>assert.equal(buildLaborerSavePayload(FORM,{contractorId:'C1',isNew:false}).salary_days,SYSTEM.payroll.monthlyDailyDivisor));
