import test from 'node:test';
import assert from 'node:assert/strict';
import { CONTRACTOR_DATE_STATE, INTEGRITY_ISSUE, LIVE_OPERATION_BLOCKER, auditProjectOperationIntegrity, buildProjectOperationRoster, detectOperationIntegrityIssues, resolveProjectOperationRoster, rosterContractorsAvailableForNewLiveOperation, rosterContractorsEligibleForSelectedDate, rosterLaborersAvailableForNewLiveOperation, rosterLaborersEligibleForSelectedDate } from '../lib/operations-governance.js';
const DATE='2026-08-15';
const contractor=(id='C1',active=true)=>({id,name_ar:`مقاول ${id}`,is_active:active});
const laborer=(id='L1',active=true)=>({id,full_name:`عامل ${id}`,labor_class:'worker',is_active:active});
const engagement=(overrides={})=>({id:'PC1',contractor_id:'C1',start_date:'2026-08-01',end_date:null,is_active:true,...overrides});
const assignment=(overrides={})=>({id:'A1',laborer_id:'L1',contractor_id:'C1',valid_from:'2026-08-01',valid_to:null,labor_class:'worker',...overrides});
const roster=(overrides={})=>buildProjectOperationRoster({projectId:'P1',date:DATE,projectContractors:[engagement()],assignments:[assignment()],contractors:[contractor()],laborers:[laborer()],...overrides});

test('contractor assigned with zero laborers stays visible',()=>{const r=roster({assignments:[],laborers:[]});assert.equal(r.contractors.length,1);assert.equal(r.contractors[0].relationshipDateEligible,true);assert.equal(r.contractors[0].hasNoLaborersLoaded,true);});
test('missing contractor entity fails safe',()=>{const r=roster({contractors:[]});const c=r.contractors[0];assert.equal(c.contractorEntityActiveNow,false);assert.equal(c.availableForNewLiveOperation,false);assert.ok(c.liveOperationBlockers.includes(LIVE_OPERATION_BLOCKER.MISSING_CONTRACTOR_ENTITY));assert.ok(r.integrityIssues.some(i=>i.type===INTEGRITY_ISSUE.MISSING_CONTRACTOR_ENTITY));});
test('missing laborer entity fails safe',()=>{const r=roster({laborers:[]});const l=r.contractors[0].laborers[0];assert.equal(l.laborerEntityActiveNow,false);assert.equal(l.availableForNewLiveOperation,false);assert.ok(l.liveOperationBlockers.includes(LIVE_OPERATION_BLOCKER.MISSING_LABORER_ENTITY));});
test('historical date eligibility is separate from current enabled state',()=>{const r=roster({date:'2026-08-10',projectContractors:[engagement({start_date:'2026-08-01',end_date:'2026-08-20',is_active:false})],assignments:[assignment({valid_from:'2026-08-05',valid_to:'2026-08-15'})]});const c=r.contractors[0],l=c.laborers[0];assert.equal(c.relationshipDateEligible,true);assert.equal(c.relationshipEnabledNow,false);assert.equal(l.eligibleForSelectedDate,true);assert.equal(l.availableForNewLiveOperation,false);assert.equal(r.hasDataIntegrityIssues,false);});
test('inactive entities block new live operation without rewriting history',()=>{const r=roster({contractors:[contractor('C1',false)],laborers:[laborer('L1',false)]});const l=r.contractors[0].laborers[0];assert.equal(l.eligibleForSelectedDate,true);assert.equal(l.availableForNewLiveOperation,false);assert.equal(r.hasDataIntegrityIssues,false);});
test('assignment is_active is not temporal authority',()=>{const l=roster({assignments:[assignment({is_active:false})]}).contractors[0].laborers[0];assert.equal(l.assignmentDateEligible,true);assert.equal(l.availableForNewLiveOperation,true);});
test('multiple engagement periods select the period covering the date',()=>{const r=roster({date:'2026-08-25',projectContractors:[engagement({id:'PC1',start_date:'2026-08-01',end_date:'2026-08-10',is_active:false}),engagement({id:'PC2',start_date:'2026-08-20',end_date:null,is_active:true})],assignments:[assignment({valid_from:'2026-08-20'})]});assert.equal(r.contractors[0].engagements.length,2);assert.equal(r.contractors[0].selectedEngagement.id,'PC2');});
test('assignment inside second engagement is valid',()=>{const pcs=[engagement({id:'PC1',start_date:'2026-08-01',end_date:'2026-08-10'}),engagement({id:'PC2',start_date:'2026-08-20',end_date:null})];assert.deepEqual(detectOperationIntegrityIssues(pcs,[assignment({valid_from:'2026-08-22',valid_to:'2026-08-30'})]),[]);});
test('assignment in engagement gap is an integrity issue',()=>{const pcs=[engagement({id:'PC1',start_date:'2026-08-01',end_date:'2026-08-10'}),engagement({id:'PC2',start_date:'2026-08-20',end_date:null})];assert.equal(detectOperationIntegrityIssues(pcs,[assignment({valid_from:'2026-08-12',valid_to:'2026-08-15'})])[0].type,INTEGRITY_ISSUE.OUTSIDE_ENGAGEMENT_PERIOD);});
test('assignment spanning two periods and their gap is invalid',()=>{const pcs=[engagement({id:'PC1',start_date:'2026-08-01',end_date:'2026-08-10'}),engagement({id:'PC2',start_date:'2026-08-20',end_date:'2026-08-30'})];assert.equal(detectOperationIntegrityIssues(pcs,[assignment({valid_from:'2026-08-05',valid_to:'2026-08-25'})])[0].type,INTEGRITY_ISSUE.OUTSIDE_ENGAGEMENT_PERIOD);});
test('orphan assignment cannot create relationship eligibility',()=>{const r=roster({projectContractors:[]});assert.equal(r.hasNoContractorEngagements,true);assert.equal(r.summary.eligibleForSelectedDateContractorCount,0);assert.equal(r.summary.eligibleForSelectedDateLaborerCount,0);assert.equal(r.contractors[0].dateState,CONTRACTOR_DATE_STATE.NONE);});
test('selectors distinguish historical eligibility from new-live availability',()=>{const r=roster({projectContractors:[engagement({is_active:false})]});assert.equal(rosterContractorsEligibleForSelectedDate(r).length,1);assert.equal(rosterContractorsAvailableForNewLiveOperation(r).length,0);assert.equal(rosterLaborersEligibleForSelectedDate(r,'C1').length,1);assert.equal(rosterLaborersAvailableForNewLiveOperation(r,'C1').length,0);});
function fakeSupabase(tables){return{from(table){const rows=tables[table]||[],filters=[];const b={select(){return b;},eq(c,v){filters.push(r=>r[c]===v);return b;},in(c,vs){filters.push(r=>vs.includes(r[c]));return b;},lte(c,v){filters.push(r=>r[c]!=null&&r[c]<=v);return b;},or(expr){const clauses=expr.split(',').map(clause=>{const[c,op,v]=clause.split('.');return r=>op==='is'&&v==='null'?r[c]==null:op==='gte'?r[c]!=null&&r[c]>=v:false;});filters.push(r=>clauses.some(fn=>fn(r)));return b;},then(resolve,reject){try{resolve({data:rows.filter(r=>filters.every(fn=>fn(r))),error:null});}catch(e){reject(e);}}};return b;}};}
test('integration: contractor is operable with zero laborers then labor appears after assignment',async()=>{const tables={project_contractors:[{project_id:'P1',...engagement()}],labor_project_assignments:[],contractors:[contractor()],laborers:[]};const s=fakeSupabase(tables);const before=await resolveProjectOperationRoster({supabase:s,projectId:'P1',date:DATE});assert.equal(before.contractors[0].hasNoLaborersLoaded,true);tables.labor_project_assignments.push({project_id:'P1',...assignment()});tables.laborers.push(laborer());const after=await resolveProjectOperationRoster({supabase:s,projectId:'P1',date:DATE});assert.equal(after.summary.availableForNewLiveOperationLaborerCount,1);});
test('integration: live resolver is date-scoped while audit catches stale history',async()=>{const tables={project_contractors:[{project_id:'P1',...engagement()}],labor_project_assignments:[{project_id:'P1',...assignment({id:'CURRENT',laborer_id:'L1'})},{project_id:'P1',...assignment({id:'OLD',laborer_id:'L2',contractor_id:'C2',valid_from:'2021-01-01',valid_to:'2021-02-01'})}],contractors:[contractor()],laborers:[laborer('L1'),laborer('L2')]};const s=fakeSupabase(tables);const live=await resolveProjectOperationRoster({supabase:s,projectId:'P1',date:DATE});assert.equal(live.integrityIssues.some(i=>i.assignment?.id==='OLD'),false);const audit=await auditProjectOperationIntegrity({supabase:s,projectId:'P1'});assert.equal(audit.integrityIssues.some(i=>i.assignment?.id==='OLD'),true);});
