'use client';
import { useEffect, useState, useCallback } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { dateAr, money } from '@/lib/format';

const OSTATUS={draft:'مسودة',internal_review:'تحت المراجعة الداخلية',internal_approved:'معتمد داخلياً',sent:'أُرسل للمرشح',accepted:'مقبول من المرشح',declined:'اعتذر المرشح',expired:'منتهي الصلاحية',superseded:'نسخة مستبدلة'};

export default function OfferEditor(){
  const {id}=useParams();
  const [app,setApp]=useState(null),[offer,setOffer]=useState(null),[employees,setEmployees]=useState([]),[approver,setApprover]=useState(''),[evidence,setEvidence]=useState(''),[code,setCode]=useState(''),[err,setErr]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{
    const [a,o,e]=await Promise.all([
      supabase.from('candidate_applications').select('*,candidates(*),job_vacancies(*)').eq('id',id).maybeSingle(),
      supabase.from('job_offers').select('*').eq('application_id',id).order('offer_version',{ascending:false}).limit(1).maybeSingle(),
      supabase.from('employees').select('id,full_name_ar,job_title,board_role').eq('status','active').order('full_name_ar')
    ]);
    if(a.error||o.error||e.error)setErr(a.error?.message||o.error?.message||e.error?.message);
    setApp(a.data);setOffer(o.data||null);setEmployees(e.data||[]);
    if(o.data?.internal_approved_by_employee_id)setApprover(o.data.internal_approved_by_employee_id);
    if(o.data?.internal_approval_evidence)setEvidence(o.data.internal_approval_evidence);
  },[id]);
  useEffect(()=>{load();},[load]);
  const flash=m=>{setSaved(m);setTimeout(()=>setSaved(''),1700)};
  async function createOffer(){setBusy(true);const {data,error}=await supabase.rpc('create_job_offer_from_application',{p_application:id,p_valid_days:7});setBusy(false);if(error){setErr(error.message);return;}flash('أُنشئت مسودة العرض');load();}
  async function patch(fields){setOffer({...offer,...fields});const {error}=await supabase.from('job_offers').update({...fields,updated_at:new Date().toISOString()}).eq('id',offer.id);if(error)setErr(error.message);else flash('حُفظ');}
  async function approve(){if(!approver){setErr('اختر صاحب الاعتماد الفعلي');return;}setBusy(true);const {error}=await supabase.rpc('approve_job_offer_internal',{p_offer:offer.id,p_approver_employee:approver,p_evidence:evidence||null,p_company_signature:true,p_company_stamp:true});setBusy(false);if(error){setErr(error.message);return;}flash('سُجل الاعتماد الداخلي');load();}
  async function prepareCode(){setBusy(true);const {data,error}=await supabase.rpc('prepare_job_offer_verification',{p_offer:offer.id,p_channel:'whatsapp'});setBusy(false);if(error){setErr(error.message);return;}setCode(data);flash('تم إنشاء رمز التحقق — صالح لمدة ساعة');load();}
  async function copy(text,msg){await navigator.clipboard.writeText(text);flash(msg);}
  if(!app)return <div className="empty">جارٍ تحميل المرشح…</div>;
  const c=app.candidates||{},v=app.job_vacancies||{};
  if(!offer)return <><div className="page-head"><div><h1>العرض الوظيفي</h1><p>{c.full_name_ar} — {v.title_ar}</p></div><Link className="btn ghost" href={`/dashboard/recruitment/applications/${id}`}>ملف المرشح</Link></div><div className="section" style={{padding:24,marginTop:0}}><h2 style={{marginTop:0}}>إنشاء العرض من نتيجة الترشيح</h2><p style={{lineHeight:1.9}}>سينشئ النظام مسودة مستقلة تحفظ بيانات المرشح والشاغر في لحظة الإنشاء. أي تعديل لاحق بعد إرسال العرض يحتاج نسخة جديدة وقبولاً جديداً.</p>{err&&<div className="msg err">{err}</div>}<button className="btn" onClick={createOffer} disabled={busy}>{busy?'جارٍ الإنشاء…':'إنشاء مسودة العرض الوظيفي'}</button></div></>;
  const editable=['draft','internal_review'].includes(offer.status);
  const link=typeof window!=='undefined'?`${window.location.origin}/offers/${offer.public_token}`:'';
  const gross=offer.salary_display_mode==='detailed'?[offer.basic_salary,offer.housing_allowance,offer.transport_allowance,offer.other_allowance].reduce((s,x)=>s+Number(x||0),0):Number(offer.gross_salary||0);
  return <>
    <div className="page-head"><div><h1>العرض الوظيفي</h1><p>{c.full_name_ar} — النسخة {offer.offer_version} — {OSTATUS[offer.status]||offer.status}</p></div><div className="rowsplit"><Link className="btn ghost" href={`/dashboard/recruitment/applications/${id}`}>ملف المرشح</Link>{['sent','accepted','declined'].includes(offer.status)&&<button className="btn ghost" onClick={()=>window.open(link,'_blank')}>معاينة رابط المرشح</button>}</div></div>
    {err&&<div className="msg err" style={{marginBottom:12}}>{err}</div>}{saved&&<div className="msg ok" style={{marginBottom:12}}>{saved}</div>}
    <div className="grid k4" style={{marginBottom:16}}><div className="card"><h3>المرشح</h3><div className="big" style={{fontSize:18}}>{offer.candidate_name_snapshot}</div></div><div className="card"><h3>الوظيفة</h3><div className="big" style={{fontSize:18}}>{offer.job_title_snapshot}</div></div><div className="card"><h3>الراتب المعروض</h3><div className="big" style={{fontSize:20}}>{gross?money(gross):'—'}</div></div><div className="card"><h3>صلاحية العرض</h3><div className="big" style={{fontSize:18}}>{dateAr(offer.valid_until)}</div></div></div>

    <div className="section" style={{marginTop:0,padding:18}}><header style={{margin:'-18px -18px 16px'}}><h2>بيانات العرض</h2></header><div className="form-grid">
      <div className="field span2"><label>المسمى الوظيفي</label><input disabled={!editable} value={offer.job_title_snapshot||''} onChange={e=>setOffer({...offer,job_title_snapshot:e.target.value})} onBlur={e=>editable&&patch({job_title_snapshot:e.target.value})}/></div><div className="field"><label>الإدارة</label><input disabled={!editable} value={offer.department_snapshot||''} onChange={e=>setOffer({...offer,department_snapshot:e.target.value})} onBlur={e=>editable&&patch({department_snapshot:e.target.value||null})}/></div>
      <div className="field"><label>طريقة عرض الراتب</label><select disabled={!editable} value={offer.salary_display_mode} onChange={e=>patch({salary_display_mode:e.target.value})}><option value="gross_only">إجمالي فقط</option><option value="detailed">تفصيلي</option></select></div>
      {offer.salary_display_mode==='gross_only'?<div className="field"><label>إجمالي الراتب</label><input disabled={!editable} type="number" value={offer.gross_salary??''} onChange={e=>setOffer({...offer,gross_salary:e.target.value})} onBlur={e=>editable&&patch({gross_salary:e.target.value===''?null:Number(e.target.value)})}/></div>:<><div className="field"><label>الراتب الأساسي</label><input disabled={!editable} type="number" value={offer.basic_salary??''} onChange={e=>setOffer({...offer,basic_salary:e.target.value})} onBlur={e=>editable&&patch({basic_salary:e.target.value===''?null:Number(e.target.value)})}/></div><div className="field"><label>بدل السكن</label><input disabled={!editable} type="number" value={offer.housing_allowance??''} onChange={e=>setOffer({...offer,housing_allowance:e.target.value})} onBlur={e=>editable&&patch({housing_allowance:e.target.value===''?null:Number(e.target.value)})}/></div><div className="field"><label>بدل النقل</label><input disabled={!editable} type="number" value={offer.transport_allowance??''} onChange={e=>setOffer({...offer,transport_allowance:e.target.value})} onBlur={e=>editable&&patch({transport_allowance:e.target.value===''?null:Number(e.target.value)})}/></div><div className="field"><label>بدلات أخرى</label><input disabled={!editable} type="number" value={offer.other_allowance??''} onChange={e=>setOffer({...offer,other_allowance:e.target.value})} onBlur={e=>editable&&patch({other_allowance:e.target.value===''?null:Number(e.target.value)})}/></div></>}
      <div className="field"><label>ساعات العمل الفعلية يومياً</label><input disabled={!editable} type="number" step="0.5" value={offer.daily_work_hours} onChange={e=>patch({daily_work_hours:Number(e.target.value||8)})}/></div><div className="field"><label>فترة التجربة (يوم)</label><input disabled={!editable} type="number" min="0" value={offer.probation_days} onChange={e=>patch({probation_days:Number(e.target.value||0)})}/></div><div className="field"><label>الإجازة السنوية (يوم)</label><input disabled={!editable} type="number" value={offer.annual_leave_days??''} onChange={e=>setOffer({...offer,annual_leave_days:e.target.value})} onBlur={e=>editable&&patch({annual_leave_days:e.target.value===''?null:Number(e.target.value)})}/></div><div className="field"><label>المباشرة المتوقعة</label><input disabled={!editable} type="date" value={offer.expected_start_date||''} onChange={e=>patch({expected_start_date:e.target.value||null})}/></div>
      <div className="field"><label>صلاحية العرض بالأيام</label><input disabled={!editable} type="number" min="1" max="90" value={offer.valid_days} onChange={e=>{const d=Number(e.target.value||7);const until=new Date();until.setDate(until.getDate()+d);patch({valid_days:d,valid_until:until.toISOString().slice(0,10)})}}/></div><div className="field span3"><label>الشروط والملاحظات الخاصة</label><textarea disabled={!editable} rows="4" value={offer.conditions_text||''} onChange={e=>setOffer({...offer,conditions_text:e.target.value})} onBlur={e=>editable&&patch({conditions_text:e.target.value||null})}/></div>
    </div></div>

    {editable&&<div className="section"><header><h2>اعتماد الطرف الأول</h2></header><div style={{padding:18}}><p style={{fontSize:13.5,lineHeight:1.8}}>يسجل النظام هنا الاعتماد الحقيقي بعد مراجعته داخلياً. يمكن أن يكون الاعتماد ورقياً، ويقوم مستخدم النظام بتوثيق اسم صاحب الاعتماد وطريقته.</p><div className="form-grid"><div className="field span2"><label>صاحب الاعتماد الفعلي *</label><select value={approver} onChange={e=>setApprover(e.target.value)}><option value="">اختر…</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name_ar}{e.board_role?` — ${e.board_role}`:e.job_title?` — ${e.job_title}`:''}</option>)}</select></div><div className="field span2"><label>مرجع / طريقة الاعتماد</label><input value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="مثال: نسخة ورقية موقعة أو موافقة مكتوبة"/></div></div><button className="btn" style={{marginTop:12}} onClick={approve} disabled={busy}>{busy?'جارٍ التسجيل…':'تسجيل الاعتماد الداخلي'}</button></div></div>}

    {['internal_approved','sent'].includes(offer.status)&&<div className="section"><header><h2>إرسال العرض للمرشح</h2></header><div style={{padding:18}}><div className="form-grid"><div className="field span3"><label>رابط العرض</label><div className="rowsplit"><input readOnly dir="ltr" value={link}/><button className="btn ghost" type="button" onClick={()=>copy(link,'تم نسخ الرابط')}>نسخ</button></div></div></div><p className="hint" style={{marginTop:10}}>أنشئ رمز التحقق ثم أرسله للمرشح عبر واتساب مع الرابط. الرمز صالح لمدة ساعة ويمكن إصدار رمز جديد عند الحاجة.</p><button className="btn" onClick={prepareCode} disabled={busy}>{busy?'جارٍ الإنشاء…':'إنشاء رمز تحقق من 8 أرقام'}</button>{code&&<div className="msg ok" style={{marginTop:12,fontSize:22,fontWeight:700,direction:'ltr',textAlign:'center'}}>{code}<button className="btn ghost" style={{marginLeft:12}} onClick={()=>copy(code,'تم نسخ الرمز')}>نسخ</button></div>}</div></div>}

    {offer.status==='accepted'&&<div className="msg ok" style={{lineHeight:1.8}}>وافق المرشح على العرض بتاريخ {dateAr(offer.candidate_accepted_at)}. أنشأ النظام مسودة العقد تلقائياً للمراجعة الداخلية.</div>}
    {offer.status==='declined'&&<div className="msg" style={{lineHeight:1.8}}>اعتذر المرشح عن العرض. {offer.candidate_comment||''}</div>}
  </>;
}
