'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useDashboardSession } from '@/lib/dashboard-session-context';
import { FOCUS_VALVE_STATE } from '@/lib/focus-valve-constitution';
import { FocusValve, FocusReady, FocusRegister, FocusWork, FocusContextLine } from '@/components/ui/FocusValve';
import { attendanceLabWorkspaceService } from '@/lib/application/attendance-lab-workspace-service';
import AttendanceCalibrationPanel from '@/components/attendance/AttendanceCalibrationPanel';
import AttendanceClientExcelReport from '@/components/attendance/AttendanceClientExcelReport';
import AttendanceProcessingTable from '@/components/attendance/AttendanceProcessingTable';
import AttendanceJustificationDialog from '@/components/attendance/AttendanceJustificationDialog';

const WEEKDAYS=[
  {weekday:0,label:'الأحد'},{weekday:1,label:'الاثنين'},{weekday:2,label:'الثلاثاء'},
  {weekday:3,label:'الأربعاء'},{weekday:4,label:'الخميس'},{weekday:5,label:'الجمعة'},{weekday:6,label:'السبت'},
];
const STATUS_AR={complete:'مكتمل',missing_in:'بصمة دخول مفقودة',missing_out:'بصمة خروج مفقودة',absent:'غياب',day_off:'إجازة',no_schedule:'ساعات الدوام غير محددة',needs_review:'يحتاج مراجعة'};
const STAGE_AR={uploaded:'مرفوع',parsed:'تم الاستخراج',calibrated:'تمت معايرة ساعات الدوام',analyzed:'تم التحليل',justifications:'معالجة التبريرات',recalculated:'أعيد الاحتساب',ready_to_post:'جاهز للترحيل / التسليم',posted:'مرحّل إلى HR',closed:'مغلق ومسلّم',failed:'فشل',superseded:'مستبدل'};
const STAGE_ORDER=['parsed','calibrated','analyzed','justifications','recalculated','ready_to_post','posted'];

function blankDays(){return WEEKDAYS.map((day)=>({...day,is_workday:day.weekday!==5,start_time:'',end_time:'',notes:''}));}
function localTimestamp(date){const pad=(n)=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;}
function normalizePunchTimestamp(value){const text=String(value??'').trim();if(!text)return '';const match=text.match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{1,2}):(\d{2})(?::(\d{2}))?/);if(match)return `${match[1]}-${match[2]}-${match[3]}T${String(match[4]).padStart(2,'0')}:${match[5]}:${match[6]||'00'}`;const date=new Date(text);return Number.isNaN(date.getTime())?'':localTimestamp(date);}
function stageIndex(status){if(status==='closed')return STAGE_ORDER.length;return STAGE_ORDER.indexOf(status);}
function eventDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?String(value||''):new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date);}

export default function AttendanceLabWorkspaceEngineered(){
  const me=useDashboardSession();
  const isPrimary=me?.actionContext?.isPrimaryUser===true;
  const canPost=isPrimary||me?.capabilityKeys?.has?.('hr.attendance.post');

  const [imports,setImports]=useState([]);const [activeId,setActiveId]=useState('');const [activeImport,setActiveImport]=useState(null);const [days,setDays]=useState([]);const [events,setEvents]=useState([]);const [employees,setEmployees]=useState([]);const [externalPeople,setExternalPeople]=useState([]);
  const [newScope,setNewScope]=useState('internal');const [clientName,setClientName]=useState('');const [clientReference,setClientReference]=useState('');const [file,setFile]=useState(null);const [parsedRows,setParsedRows]=useState([]);
  const [subjectId,setSubjectId]=useState('');const [scheduleId,setScheduleId]=useState(null);const [scheduleName,setScheduleName]=useState('الدوام الأساسي');const [validFrom,setValidFrom]=useState('');const [validTo,setValidTo]=useState('');const [scheduleDays,setScheduleDays]=useState(blankDays());const [bulkStart,setBulkStart]=useState('');const [bulkEnd,setBulkEnd]=useState('');
  const [selectedDay,setSelectedDay]=useState(null);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const [msg,setMsg]=useState('');

  const punchCount=useMemo(()=>parsedRows.filter((row)=>row.punch_local).length,[parsedRows]);
  const summary=useMemo(()=>days.reduce((acc,day)=>{acc.total+=1;acc[day.day_status]=(acc[day.day_status]||0)+1;acc.pre+=Number(day.preliminary_deduction_days||0);acc.final+=Number(day.final_deduction_days||0);acc.work+=Number(day.worked_minutes||0);return acc;},{total:0,complete:0,missing_in:0,missing_out:0,absent:0,day_off:0,no_schedule:0,needs_review:0,pre:0,final:0,work:0}),[days]);

  async function loadImports(selectId=null,ignoreCurrent=false){try{const list=await attendanceLabWorkspaceService.listImports(30);setImports(list);const target=selectId||(!ignoreCurrent?activeId:'')||'';if(target!==activeId)setActiveId(target);}catch(error){setErr(error.message||String(error));}}
  async function loadEmployees(){try{setEmployees(await attendanceLabWorkspaceService.listEmployees());}catch(error){setErr(error.message||String(error));}}
  async function loadActive(id){if(!id){setActiveImport(null);setDays([]);setEvents([]);setExternalPeople([]);return;}try{const workspace=await attendanceLabWorkspaceService.loadImport(id);setActiveImport(workspace.activeImport);setDays(workspace.days);setEvents(workspace.events);setExternalPeople(workspace.externalPeople);setSubjectId('');setScheduleId(null);setScheduleName('الدوام الأساسي');setValidFrom(workspace.activeImport?.period_from||'');setValidTo(workspace.activeImport?.period_to||'');setScheduleDays(blankDays());}catch(error){setActiveImport(null);setDays([]);setEvents([]);setExternalPeople([]);setErr(error.message||String(error));}}

  useEffect(()=>{loadEmployees();loadImports();},[]);
  useEffect(()=>{loadActive(activeId);},[activeId]);

  async function readAttendanceFile(nextFile){setErr('');setMsg('');setFile(nextFile||null);setParsedRows([]);if(!nextFile)return;try{const XLSX=await import('xlsx');const workbook=XLSX.read(await nextFile.arrayBuffer(),{type:'array',cellDates:true});const rows=[];const roster=new Map();workbook.SheetNames.forEach((sheetName)=>{const matrix=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,raw:false,dateNF:'yyyy-mm-dd hh:mm:ss',defval:''});let sheetIdentity=null;matrix.forEach((row,index)=>{const name=String(row?.[0]??'').trim();const no=String(row?.[1]??'').trim();if((name||no)&&!sheetIdentity)sheetIdentity={employee_name:name||sheetName,employee_no:no,source_sheet:sheetName};if(name||no)roster.set(`${no}|${name||sheetName}`,{employee_name:name||sheetName,employee_no:no,source_sheet:sheetName});const punch=normalizePunchTimestamp(row?.[2]);if(!punch)return;rows.push({employee_name:name||sheetIdentity?.employee_name||sheetName,employee_no:no||sheetIdentity?.employee_no||'',punch_local:punch,source_sheet:sheetName,source_row:index+1,raw_payload:row?.[3]?{source_note:String(row[3])}:{}});});if(!sheetIdentity&&sheetName)roster.set(`|${sheetName}`,{employee_name:sheetName,employee_no:'',source_sheet:sheetName});});roster.forEach((person)=>rows.push({...person,punch_local:'',source_row:null,raw_payload:{roster_only:true}}));if(!rows.some((row)=>row.punch_local)){setErr('لم أجد حركات بصمة قابلة للقراءة في الملف.');return;}setParsedRows(rows);}catch(error){setErr('تعذر قراءة ملف Excel: '+(error.message||error));}}
  async function sha256(nextFile){if(!globalThis.crypto?.subtle)return null;const digest=await crypto.subtle.digest('SHA-256',await nextFile.arrayBuffer());return Array.from(new Uint8Array(digest)).map((byte)=>byte.toString(16).padStart(2,'0')).join('');}

  async function createBatch(){if(!file||!parsedRows.length)return;if(newScope==='external'&&!clientName.trim()){setErr('اكتب اسم العميل قبل إنشاء المعالجة الخارجية.');return;}setBusy(true);setErr('');setMsg('');try{const data=await attendanceLabWorkspaceService.createBatch({file,hash:await sha256(file),rows:parsedRows,processingScope:newScope,clientName,clientReference});setMsg(`تم استخراج ${data?.rows||0} حركة خام.`);setFile(null);setParsedRows([]);await loadImports(data?.import_id);setActiveId(data?.import_id||'');}catch(error){setErr('تعذر إنشاء دفعة المعالجة: '+(error.message||error));}finally{setBusy(false);}}

  async function loadSchedule(id){setSubjectId(id);setScheduleId(null);setScheduleName('الدوام الأساسي');setValidFrom(activeImport?.period_from||'');setValidTo(activeImport?.period_to||'');setScheduleDays(blankDays());if(!id||!activeImport)return;try{const result=await attendanceLabWorkspaceService.loadSchedule({activeImport,subjectId:id});if(!result)return;setScheduleId(result.schedule.id);setScheduleName(result.schedule.name||'الدوام الأساسي');setValidFrom(result.schedule.valid_from||activeImport.period_from||'');setValidTo(result.schedule.valid_to||activeImport.period_to||'');const byDay=new Map((result.days||[]).map((row)=>[Number(row.weekday),row]));setScheduleDays(WEEKDAYS.map((day)=>{const row=byDay.get(day.weekday);return {...day,is_workday:row?row.is_workday:day.weekday!==5,start_time:row?.start_time?.slice(0,5)||'',end_time:row?.end_time?.slice(0,5)||'',notes:row?.notes||''};}));}catch(error){setErr(error.message||String(error));}}
  function updateScheduleDay(weekday,patch){setScheduleDays((list)=>list.map((day)=>day.weekday===weekday?{...day,...patch}:day));}
  function applyBulkTime(){if(bulkStart&&bulkEnd)setScheduleDays((list)=>list.map((day)=>day.is_workday?{...day,start_time:bulkStart,end_time:bulkEnd}:day));}
  async function saveSchedule(){if(!activeImport||!subjectId||!validFrom){setErr('اختر الشخص وحدد بداية سريان ساعات الدوام.');return;}if(scheduleDays.some((day)=>day.is_workday&&(!day.start_time||!day.end_time))){setErr('كل يوم عمل يحتاج ساعة بداية وساعة نهاية.');return;}setBusy(true);setErr('');try{const nextId=await attendanceLabWorkspaceService.saveSchedule({activeImport,scheduleId,subjectId,name:scheduleName,validFrom,validTo,days:scheduleDays.map(({weekday,is_workday,start_time,end_time,notes})=>({weekday,is_workday,start_time,end_time,notes}))});setScheduleId(nextId);setMsg('تم حفظ ساعات الدوام.');}catch(error){setErr(error.message||String(error));}finally{setBusy(false);}}

  async function runStage(action){if(!activeImport)return;setBusy(true);setErr('');setMsg('');try{const result=await attendanceLabWorkspaceService.runStage({action,importId:activeImport.id});setMsg(result.message);await loadImports(activeImport.id);await loadActive(activeImport.id);}catch(error){setErr(error.message||String(error));}finally{setBusy(false);}}
  function openJustification(day){setSelectedDay(day);setErr('');setMsg('');}

  async function exportWorkbook(){if(!activeImport)return;setBusy(true);setErr('');try{const XLSX=await import('xlsx');const projection=await attendanceLabWorkspaceService.loadExportData(activeImport.id);const wb=XLSX.utils.book_new();const summaryRows=[['نوع المعالجة',activeImport.processing_scope==='external'?'خارجي':'داخلي'],['العميل',activeImport.client_name_snapshot||'أركان المكان'],['مرجع العميل',activeImport.client_reference||''],['الملف',activeImport.source_file_name],['الفترة من',activeImport.period_from||''],['الفترة إلى',activeImport.period_to||''],['المرحلة',STAGE_AR[activeImport.status]||activeImport.status],['إصدار المراجعة',activeImport.review_revision||0],['الحركات الخام',activeImport.rows_received||0],['غير المطابق',activeImport.unmatched_punches||0],['مكتمل',summary.complete],['غياب',summary.absent],['دخول مفقود',summary.missing_in],['خروج مفقود',summary.missing_out],['الخصم المبدئي',summary.pre],['الخصم النهائي',summary.final]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summaryRows),'ملخص');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet((projection.punches||[]).map((row)=>({'الرقم':row.external_employee_no||'','الاسم':row.external_employee_name||'','الحركة':row.punch_local,'الورقة':row.source_sheet||'','السطر':row.source_row||'','المطابقة':row.match_method||''}))),'الحركات الخام');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(days.map((day)=>({'الرقم':day.subject_no||'','الاسم':day.subject_name||'','التاريخ':day.work_date,'بداية الدوام':day.scheduled_start||'','نهاية الدوام':day.scheduled_end||'','الدخول':day.check_in||'','الخروج':day.check_out||'','دقائق العمل':day.worked_minutes??'','انحراف الدخول':day.arrival_delta_minutes??'','انحراف الخروج':day.departure_delta_minutes??'','الحالة':STATUS_AR[day.day_status]||day.day_status,'الخصم المبدئي':Number(day.preliminary_deduction_days||0),'التبرير':day.justification_text||'','قرار التبرير':day.justification_decision||'','المرجع':day.paper_reference||'','الخصم النهائي':Number(day.final_deduction_days||0),'ملاحظة التحليل':day.analysis_note||''}))),'النتائج');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet((projection.events||events||[]).map((row)=>({'المرحلة':STAGE_AR[row.stage]||row.stage,'الإجراء':row.action_key,'التاريخ':row.created_at,'الملخص':JSON.stringify(row.summary||{})}))),'سجل المعالجة');const safe=String(activeImport.client_name_snapshot||'أركان المكان').replace(/[\\/:*?"<>|]/g,'-');XLSX.writeFile(wb,`حضور_${safe}_${activeImport.status}_${activeImport.period_from||''}.xlsx`);}catch(error){setErr('تعذر إنشاء ملف التحليل: '+(error.message||error));}finally{setBusy(false);}}

  function leaveFocusedImport(){if(busy)return;setSelectedDay(null);setSubjectId('');setActiveId('');setActiveImport(null);setDays([]);setEvents([]);setExternalPeople([]);setErr('');setMsg('');}

  const subjects=activeImport?.processing_scope==='external'?externalPeople.map((person)=>({id:person.id,no:person.external_employee_no,name:person.external_employee_name})):employees.map((person)=>({id:person.id,no:person.employee_no,name:person.full_name_ar}));
  const stage=activeImport?.status;const isExternal=activeImport?.processing_scope==='external';const externalAnalysisFinished=isExternal&&stageIndex(stage)>=stageIndex('analyzed');const showAnalyticalEditors=activeImport&&!['posted','closed'].includes(stage)&&(!isExternal||!externalAnalysisFinished);const focusState=activeImport?FOCUS_VALVE_STATE.FOCUSED:FOCUS_VALVE_STATE.READY;const focusTitle=activeImport?(isExternal?(activeImport.client_name_snapshot||'دفعة عميل خارجي'):'دفعة حضور أركان المكان'):'الحضور والانصراف';const focusMeta=activeImport?[activeImport.period_from&&activeImport.period_to?`${activeImport.period_from} — ${activeImport.period_to}`:(activeImport.period_from||''),STAGE_AR[stage]||stage,activeImport.client_reference||''].filter(Boolean):[];

  return <FocusValve state={focusState} entity={activeImport?{type:'attendance-import',id:activeImport.id}:null} stage={stage}>
    <FocusReady>
      <div className="page-head"><div><h1>الحضور والانصراف</h1><p>رفع الملف، معايرة الدوام، ثم التحليل.</p></div></div>
      <div className="section" style={{marginTop:16}}><header><h2>دفعة جديدة</h2></header><div style={{padding:18}}><div className="form-grid"><div className="field"><label>نوع المعالجة</label><select value={newScope} onChange={(e)=>setNewScope(e.target.value)}><option value="internal">داخلي — أركان المكان</option><option value="external">عميل خارجي</option></select></div>{newScope==='external'&&<><div className="field"><label>اسم العميل</label><input value={clientName} onChange={(e)=>setClientName(e.target.value)}/></div><div className="field"><label>المرجع</label><input value={clientReference} onChange={(e)=>setClientReference(e.target.value)}/></div></>}</div><div className="rowsplit" style={{marginTop:16}}><label className="btn ghost" style={{cursor:'pointer'}}>اختيار Excel<input type="file" accept=".xlsx,.xls" style={{display:'none'}} onChange={(e)=>readAttendanceFile(e.target.files?.[0])}/></label>{file&&<span>{file.name}</span>}{punchCount>0&&<strong>{punchCount} حركة</strong>}<button className="btn" disabled={busy||!punchCount} onClick={createBatch}>{busy?'جارٍ الرفع…':'رفع الملف'}</button></div></div></div>
    </FocusReady>

    {err&&<div className="msg err">{err}</div>}{msg&&<div className="msg ok">{msg}</div>}

    <FocusRegister><div className="section"><header><h2>الدفعات</h2><div className="field" style={{minWidth:300}}><select value={activeId} onChange={(e)=>setActiveId(e.target.value)}><option value="">اختر دفعة</option>{imports.map((item)=><option key={item.id} value={item.id}>{item.processing_scope==='external'?(item.client_name_snapshot||'عميل خارجي'):'أركان المكان'} — {item.period_from||'بدون فترة'} — {STAGE_AR[item.status]||item.status}</option>)}</select></div></header></div></FocusRegister>

    <FocusWork>{activeImport&&<div data-attendance-focus="current-import">
      <FocusContextLine title={focusTitle} meta={focusMeta} actions={<button type="button" className="btn ghost" disabled={busy} onClick={leaveFocusedImport}>الدفعات</button>}/>
      <div className="section"><div style={{padding:18}}><div className="stat-grid"><div className="stat"><span>النوع</span><strong>{isExternal?'خارجي':'داخلي'}</strong></div><div className="stat"><span>المرحلة</span><strong>{STAGE_AR[stage]||stage}</strong></div><div className="stat"><span>الحركات</span><strong>{activeImport.rows_received||0}</strong></div><div className="stat"><span>غير مطابق</span><strong>{activeImport.unmatched_punches||0}</strong></div><div className="stat"><span>إصدار المراجعة</span><strong>{activeImport.review_revision||0}</strong></div></div><div className="rowsplit" style={{marginTop:16,gap:10,flexWrap:'wrap'}}><button className="btn ghost" disabled={busy} onClick={exportWorkbook}>{isExternal?'ملف التحليل Excel':'ملف المراجعة Excel'}</button>{!isExternal&&<AttendanceClientExcelReport activeImport={activeImport} disabled={busy||!['recalculated','ready_to_post','posted','closed'].includes(stage)}/>} {!isExternal&&stage==='analyzed'&&<button className="btn" disabled={busy} onClick={()=>runStage('review')}>بدء المراجعة</button>} {!isExternal&&['justifications','analyzed'].includes(stage)&&<button className="btn" disabled={busy} onClick={()=>runStage('recalculate')}>إعادة الاحتساب</button>} {!isExternal&&stage==='recalculated'&&<button className="btn" disabled={busy} onClick={()=>runStage('ready')}>اعتماد النتيجة</button>} {!isExternal&&stage==='ready_to_post'&&canPost&&<button className="btn" disabled={busy} onClick={()=>runStage('post')}>ترحيل إلى HR</button>} {externalAnalysisFinished&&<Link className="btn" href="/dashboard/attendance/external-review">المراجعة الخارجية</Link>}</div></div></div>

      {showAnalyticalEditors&&<AttendanceCalibrationPanel activeImport={activeImport} employees={employees} externalPeople={externalPeople} onRefresh={async()=>{if(activeImport?.id){await loadImports(activeImport.id);await loadActive(activeImport.id);}}}/>} 
      {showAnalyticalEditors&&<div className="section"><header><h2>ساعات الدوام</h2></header><div style={{padding:18}}><div className="form-grid"><div className="field"><label>{isExternal?'موظف العميل':'الموظف'}</label><select value={subjectId} onChange={(e)=>loadSchedule(e.target.value)}><option value="">اختر</option>{subjects.map((subject)=><option key={subject.id} value={subject.id}>{subject.no?`${subject.no} - `:''}{subject.name}</option>)}</select></div><div className="field"><label>الوصف</label><input value={scheduleName} onChange={(e)=>setScheduleName(e.target.value)}/></div><div className="field"><label>من</label><input type="date" value={validFrom} onChange={(e)=>setValidFrom(e.target.value)}/></div><div className="field"><label>إلى</label><input type="date" value={validTo} onChange={(e)=>setValidTo(e.target.value)}/></div></div><div className="rowsplit" style={{margin:'16px 0'}}><div className="field"><label>من</label><input type="time" value={bulkStart} onChange={(e)=>setBulkStart(e.target.value)}/></div><div className="field"><label>إلى</label><input type="time" value={bulkEnd} onChange={(e)=>setBulkEnd(e.target.value)}/></div><button type="button" className="btn ghost" onClick={applyBulkTime}>تطبيق على أيام العمل</button></div><div style={{overflowX:'auto'}}><table><thead><tr><th>اليوم</th><th>عمل</th><th>البداية</th><th>النهاية</th><th>ملاحظات</th></tr></thead><tbody>{scheduleDays.map((day)=><tr key={day.weekday}><td>{day.label}</td><td><input type="checkbox" checked={day.is_workday} onChange={(e)=>updateScheduleDay(day.weekday,{is_workday:e.target.checked,start_time:e.target.checked?day.start_time:'',end_time:e.target.checked?day.end_time:''})}/></td><td><input type="time" disabled={!day.is_workday} value={day.start_time} onChange={(e)=>updateScheduleDay(day.weekday,{start_time:e.target.value})}/></td><td><input type="time" disabled={!day.is_workday} value={day.end_time} onChange={(e)=>updateScheduleDay(day.weekday,{end_time:e.target.value})}/></td><td><input disabled={!day.is_workday} value={day.notes} onChange={(e)=>updateScheduleDay(day.weekday,{notes:e.target.value})}/></td></tr>)}</tbody></table></div><div style={{marginTop:16}}><button className="btn" disabled={busy||!subjectId} onClick={saveSchedule}>حفظ الدوام</button></div></div></div>}

      {!isExternal&&stageIndex(stage)>=stageIndex('analyzed')&&<AttendanceProcessingTable days={days} stage={stage} onOpenJustification={openJustification}/>} 
      {!isExternal&&selectedDay&&!['posted','closed'].includes(stage)&&<AttendanceJustificationDialog day={selectedDay} isPrimary={isPrimary} onClose={()=>setSelectedDay(null)} onRefresh={async()=>{await loadActive(activeImport.id);await loadImports(activeImport.id);}}/>}
      {events.length>0&&<div className="section"><header><h2>سجل المعالجة</h2></header><div style={{overflowX:'auto'}}><table><thead><tr><th>الوقت</th><th>المرحلة</th><th>الإجراء</th></tr></thead><tbody>{events.map((event)=><tr key={event.id}><td>{eventDate(event.created_at)}</td><td>{STAGE_AR[event.stage]||event.stage}</td><td>{event.action_key}</td></tr>)}</tbody></table></div></div>}
    </div>}</FocusWork>
  </FocusValve>;
}
