'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { PROJECT_ACCESS_LEVELS } from '@/lib/access-ui';

const ERROR_AR={forbidden:'هذا الحساب لا يملك صلاحية إدارة الدخول.',employee_required:'اختر الموظف أولًا.',employee_not_found:'تعذر العثور على الموظف.',employee_email_required:'يجب تسجيل بريد إلكتروني للموظف قبل إنشاء حساب الدخول.',account_exists:'يوجد حساب دخول لهذا الموظف بالفعل.',email_account_exists:'هذا البريد مرتبط بحساب آخر ولا يمكن استخدامه تلقائيًا.',project_required:'اختر مشروعًا واحدًا على الأقل لهذا المستوى.',project_not_found:'أحد المشاريع المحددة غير موجود أو لم يعد متاحًا.',invalid_access_level:'مستوى الصلاحية غير صحيح.',password_reset_failed:'تعذر تعيين كلمة المرور المؤقتة.',cannot_disable_self:'لا يمكنك تعطيل حسابك الحالي من هذه الشاشة.',primary_user_protected:'المستخدم الرئيسي محمي ولا تُعدل صلاحياته من هذه الشاشة.'};
const MANAGED_BUNDLES=new Set(['projects_full_access','project_site_supervisor','project_manager','project_supervisor','project_originator']);
function projectLabel(p){return `${p.project_no||'—'} — ${p.name_ar}${p.city?` · ${p.city}`:''}`;}
function levelForGrants(grants,bundleById){const active=grants.filter(g=>g.is_active&&bundleById.has(g.bundle_id));const x=active.map(g=>({...g,bundle:bundleById.get(g.bundle_id)}));if(x.some(g=>g.bundle.bundle_key==='projects_full_access'&&g.scope_type==='all'))return{key:'projects_portal_full',projectIds:[]};const full=x.filter(g=>g.bundle.bundle_key==='projects_full_access'&&g.scope_type==='project').map(g=>g.scope_key);if(full.length)return{key:'project_supervisor',projectIds:[...new Set(full)]};const site=x.filter(g=>g.bundle.bundle_key==='project_site_supervisor'&&g.scope_type==='project').map(g=>g.scope_key);if(site.length)return{key:'site_supervisor',projectIds:[...new Set(site)]};return{key:'projects_portal_full',projectIds:[]};}

export default function SystemUserPage(){
 const[directory,setDirectory]=useState(null),[err,setErr]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(''),[credentials,setCredentials]=useState(null),[selectedUserId,setSelectedUserId]=useState('');
 const[newAccount,setNewAccount]=useState({employeeId:'',accessLevel:'projects_portal_full',projectIds:[]});const[editAccess,setEditAccess]=useState({accessLevel:'projects_portal_full',projectIds:[]});
 async function callAdmin(body){const{data,error}=await supabase.functions.invoke('system-user-admin',{body});if(error)throw error;if(data?.error)throw new Error(data.message||ERROR_AR[data.error]||data.error);return data;}
 async function load(keepSelection=true){setErr('');try{const data=await callAdmin({action:'directory'});const visibleUsers=(data.users||[]).filter(u=>u.employee_id||u.id===data.primaryUserId);const clean={...data,users:visibleUsers};setDirectory(clean);const next=keepSelection&&selectedUserId&&visibleUsers.some(u=>u.id===selectedUserId)?selectedUserId:(visibleUsers.find(u=>u.id!==data.primaryUserId)?.id||data.primaryUserId||'');setSelectedUserId(next);}catch(error){setErr(error.message||'تعذر تحميل إدارة الدخول.');setDirectory({employees:[],users:[],grants:[],bundles:[],projects:[],primaryUserId:null});}}
 useEffect(()=>{load(false);},[]);
 const employeeById=useMemo(()=>new Map((directory?.employees||[]).map(e=>[e.id,e])),[directory]);const bundleById=useMemo(()=>new Map((directory?.bundles||[]).filter(b=>MANAGED_BUNDLES.has(b.bundle_key)).map(b=>[b.id,b])),[directory]);const accountEmployeeIds=useMemo(()=>new Set((directory?.users||[]).map(u=>u.employee_id).filter(Boolean)),[directory]);const availableEmployees=useMemo(()=>(directory?.employees||[]).filter(e=>e.status!=='terminated'&&!accountEmployeeIds.has(e.id)),[directory,accountEmployeeIds]);const selectedUser=useMemo(()=>(directory?.users||[]).find(u=>u.id===selectedUserId)||null,[directory,selectedUserId]);const selectedEmployee=selectedUser?employeeById.get(selectedUser.employee_id):null;const selectedGrants=useMemo(()=>(directory?.grants||[]).filter(g=>g.user_id===selectedUserId),[directory,selectedUserId]);const detectedAccess=useMemo(()=>levelForGrants(selectedGrants,bundleById),[selectedGrants,bundleById]);
 useEffect(()=>{setEditAccess(detectedAccess);},[selectedUserId,detectedAccess.key,JSON.stringify(detectedAccess.projectIds)]);
 function toggleProject(setter,id){setter(c=>({...c,projectIds:c.projectIds.includes(id)?c.projectIds.filter(x=>x!==id):[...c.projectIds,id]}));}
 async function provision(e){e.preventDefault();setBusy('provision');setErr('');setMsg('');setCredentials(null);try{const data=await callAdmin({action:'provision',...newAccount});setCredentials({email:data.account.email,password:data.temporaryPassword,name:data.account.displayName});setMsg('تم إنشاء الحساب. يبدأ المستخدم من صفحة اليوم، ويجب عليه تغيير كلمة المرور عند أول دخول.');setNewAccount({employeeId:'',accessLevel:'projects_portal_full',projectIds:[]});await load(false);setSelectedUserId(data.account.userId);}catch(error){setErr(error.message||'تعذر إنشاء الحساب.');}setBusy('');}
 async function saveAccess(){if(!selectedUser||selectedUser.id===directory.primaryUserId)return;setBusy('access');setErr('');setMsg('');try{await callAdmin({action:'set_access_level',userId:selectedUser.id,...editAccess});setMsg('تم حفظ مستوى الوصول. صفحة اليوم ستتكيف تلقائيًا مع الصلاحية الجديدة.');await load();}catch(error){setErr(error.message||'تعذر حفظ الصلاحية.');}setBusy('');}
 async function resetPassword(){if(!selectedUser||selectedUser.id===directory.primaryUserId)return;setBusy('reset');setErr('');setMsg('');setCredentials(null);try{const data=await callAdmin({action:'reset_password',userId:selectedUser.id});setCredentials({email:selectedUser.auth_email||selectedEmployee?.email||'',password:data.temporaryPassword,name:selectedEmployee?.full_name_ar||selectedUser.auth_email||'المستخدم'});setMsg('تم تعيين كلمة مرور مؤقتة جديدة، وسيُطلب تغييرها عند أول دخول.');await load();}catch(error){setErr(error.message||'تعذر إعادة تعيين كلمة المرور.');}setBusy('');}
 async function setActive(isActive){if(!selectedUser||selectedUser.id===directory.primaryUserId)return;setBusy('status');setErr('');setMsg('');try{await callAdmin({action:'set_active',userId:selectedUser.id,isActive});setMsg(isActive?'تم تفعيل الحساب.':'تم تعطيل الحساب ومنع الدخول.');await load();}catch(error){setErr(error.message||'تعذر تحديث حالة الحساب.');}setBusy('');}
 async function copy(value,label){await navigator.clipboard.writeText(value);setMsg(`تم نسخ ${label}.`);}
 if(!directory)return <div className="empty">جارٍ تحميل إدارة الدخول…</div>;
 const newLevel=PROJECT_ACCESS_LEVELS.find(l=>l.key===newAccount.accessLevel)||PROJECT_ACCESS_LEVELS[0];const editLevel=PROJECT_ACCESS_LEVELS.find(l=>l.key===editAccess.accessLevel)||PROJECT_ACCESS_LEVELS[0];
 return <><div className="page-head"><div><h1>إدارة الدخول</h1><p>الصلاحيات تبدأ من البوابة ثم تضيق إلى مشروع أو أدوات محددة — وصفحة اليوم متاحة لكل مستخدم غير رئيسي</p></div></div>{err&&<div className="msg err" style={{marginBottom:14}}>{err}</div>}{msg&&<div className="msg ok" style={{marginBottom:14}}>{msg}</div>}
 <div className="section" style={{marginTop:0,marginBottom:16}}><header><h2>هرمية بوابة المشاريع</h2></header><div style={{padding:18,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10}}>{PROJECT_ACCESS_LEVELS.map((level,index)=><div key={level.key} className="card"><h3>المستوى {index+1} — {level.label}</h3><div className="foot" style={{lineHeight:1.7}}>{level.description}</div></div>)}</div></div>
 {credentials&&<div className="section" style={{marginTop:0,marginBottom:16,border:'1px solid #b7d8c8'}}><header><h2>بيانات دخول مؤقتة — تظهر الآن فقط</h2></header><div style={{padding:18}}><p style={{marginTop:0}}>أرسلها للمستخدم بطريقة آمنة. لا يمكن عرض كلمة المرور الحالية بعد إغلاق هذه الرسالة.</p><div className="form-grid"><div className="field span2"><label>المستخدم</label><input readOnly value={credentials.name||'—'}/></div><div className="field span2"><label>البريد الإلكتروني</label><div className="rowsplit"><input readOnly dir="ltr" value={credentials.email}/><button type="button" className="btn ghost" onClick={()=>copy(credentials.email,'البريد')}>نسخ</button></div></div><div className="field span2"><label>كلمة المرور المؤقتة</label><div className="rowsplit"><input readOnly dir="ltr" value={credentials.password}/><button type="button" className="btn ghost" onClick={()=>copy(credentials.password,'كلمة المرور')}>نسخ</button></div></div></div></div></div>}
 <div className="section" style={{marginTop:0,marginBottom:16}}><header><h2>إنشاء حساب موظف</h2></header><form onSubmit={provision} style={{padding:18}}><div className="form-grid"><div className="field span2"><label>الموظف *</label><select required value={newAccount.employeeId} onChange={e=>setNewAccount({...newAccount,employeeId:e.target.value})}><option value="">اختر الموظف</option>{availableEmployees.map(employee=><option key={employee.id} value={employee.id}>{employee.full_name_ar}{employee.job_title?` — ${employee.job_title}`:''}{employee.email?'':' — لا يوجد بريد'}</option>)}</select></div><div className="field span2"><label>مستوى الوصول *</label><select value={newAccount.accessLevel} onChange={e=>setNewAccount({...newAccount,accessLevel:e.target.value,projectIds:[]})}>{PROJECT_ACCESS_LEVELS.map(level=><option key={level.key} value={level.key}>{level.label}</option>)}</select><span className="hint">{newLevel.description}</span></div></div>{newLevel.scopeType==='project'&&<ProjectPicker projects={directory.projects||[]} selected={newAccount.projectIds} onToggle={id=>toggleProject(setNewAccount,id)}/>}<div className="rowsplit" style={{marginTop:16}}><button className="btn" disabled={busy==='provision'||!newAccount.employeeId||(newLevel.scopeType==='project'&&!newAccount.projectIds.length)}>{busy==='provision'?'جارٍ إنشاء الحساب…':'إنشاء الحساب وكلمة مرور مؤقتة'}</button><span className="hint">المستخدم غير الرئيسي يبدأ دائمًا من صفحة اليوم.</span></div></form></div>
 <div className="section"><header><h2>الحسابات الحالية</h2><span>{(directory.users||[]).length} حساب</span></header><div style={{padding:18}}><div className="field" style={{maxWidth:680}}><label>اختر الحساب</label><select value={selectedUserId} onChange={e=>setSelectedUserId(e.target.value)}><option value="">اختر المستخدم</option>{(directory.users||[]).map(user=>{const employee=employeeById.get(user.employee_id);return <option key={user.id} value={user.id}>{employee?.full_name_ar||user.auth_email||user.id}{user.id===directory.primaryUserId?' — المستخدم الرئيسي':''}</option>;})}</select></div>{selectedUser&&<><div className="grid k4" style={{marginTop:14,marginBottom:16}}><div className="card"><h3>المستخدم</h3><div className="big" style={{fontSize:17}}>{selectedEmployee?.full_name_ar||'—'}</div><div className="foot">{selectedEmployee?.job_title||'—'}</div></div><div className="card"><h3>البريد</h3><div className="big" style={{fontSize:14,direction:'ltr'}}>{selectedUser.auth_email||selectedEmployee?.email||'—'}</div></div><div className="card"><h3>الحالة</h3><div className="big" style={{fontSize:17}}>{selectedUser.is_active?'مفعّل':'معطّل'}</div><div className="foot">{selectedUser.must_change_password?'ينتظر تغيير كلمة المرور':'كلمة المرور مستقرة'}</div></div><div className="card"><h3>الوصول الحالي</h3><div className="big" style={{fontSize:16}}>{selectedUser.id===directory.primaryUserId?'كل النظام':(PROJECT_ACCESS_LEVELS.find(l=>l.key===detectedAccess.key)?.label||'—')}</div></div></div>{selectedUser.id===directory.primaryUserId?<div className="msg">المستخدم الرئيسي صاحب جميع البوابات والصلاحيات، ولا يخضع لهذه المستويات.</div>:<><div className="section" style={{margin:'0 0 14px'}}><header><h2>صلاحية المستخدم</h2></header><div style={{padding:16}}><div className="field" style={{maxWidth:620}}><label>المستوى</label><select value={editAccess.accessLevel} onChange={e=>setEditAccess({accessLevel:e.target.value,projectIds:[]})}>{PROJECT_ACCESS_LEVELS.map(level=><option key={level.key} value={level.key}>{level.label}</option>)}</select><span className="hint">{editLevel.description}</span></div>{editLevel.scopeType==='project'&&<ProjectPicker projects={directory.projects||[]} selected={editAccess.projectIds} onToggle={id=>toggleProject(setEditAccess,id)}/>}<button className="btn" style={{marginTop:14}} onClick={saveAccess} disabled={busy==='access'||(editLevel.scopeType==='project'&&!editAccess.projectIds.length)}>{busy==='access'?'جارٍ الحفظ…':'حفظ الصلاحية'}</button></div></div><div className="rowsplit" style={{justifyContent:'flex-start',gap:8}}><button className="btn ghost" onClick={resetPassword} disabled={busy==='reset'}>{busy==='reset'?'جارٍ إعادة التعيين…':'إصدار كلمة مرور مؤقتة جديدة'}</button><button className="btn ghost" onClick={()=>setActive(!selectedUser.is_active)} disabled={busy==='status'}>{selectedUser.is_active?'تعطيل الحساب':'تفعيل الحساب'}</button></div></>}</>}</div></div></>;
}
function ProjectPicker({projects,selected,onToggle}){return <div style={{marginTop:16}}><label style={{display:'block',fontWeight:700,marginBottom:8}}>المشاريع المسموح بها *</label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:8}}>{projects.map(project=><label key={project.id} style={{display:'flex',gap:8,alignItems:'center',padding:'10px 12px',border:'1px solid var(--hair)',borderRadius:10,cursor:'pointer'}}><input type="checkbox" checked={selected.includes(project.id)} onChange={()=>onToggle(project.id)}/><span>{projectLabel(project)}</span></label>)}</div></div>;}
