'use client';
import { useEffect, useState, useCallback } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { dateAr } from '@/lib/format';

const OSTATUS={pre_start:'قبل المباشرة',scheduled:'مباشرة مجدولة',started:'باشر العمل',completed:'مكتمل',cancelled:'ملغي'};
const RREC={continue:'استمرار',improvement:'استمرار مع خطة تحسين',consider_extension:'دراسة تمديد فترة التجربة إذا كان جائزاً',do_not_continue:'عدم الاستمرار'};
const n=v=>v===''||v==null?null:Number(v);

export default function OnboardingDetail(){
  const {id}=useParams();
  const [o,setO]=useState(null),[tasks,setTasks]=useState([]),[reviews,setReviews]=useState([]),[employees,setEmployees]=useState([]),[err,setErr]=useState(''),[saved,setSaved]=useState(''),[start,setStart]=useState({actual_start_date:'',work_authorization_basis:'',buddy_employee_id:''}),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const [a,t,r,e]=await Promise.all([
    supabase.from('candidate_onboarding').select('*,candidates(*),job_offers(*),employment_contract_drafts(id,status)').eq('id',id).maybeSingle(),
    supabase.from('candidate_onboarding_tasks').select('*').eq('onboarding_id',id).order('due_date',{ascending:true}),
    supabase.from('candidate_probation_reviews').select('*').eq('onboarding_id',id).order('review_day'),
    supabase.from('employees').select('id,full_name_ar,job_title,department').eq('status','active').order('full_name_ar')
  ]);if(a.error||t.error||r.error||e.error)setErr(a.error?.message||t.error?.message||r.error?.message||e.error?.message);setO(a.data);setTasks(t.data||[]);setReviews(r.data||[]);setEmployees(e.data||[]);if(a.data)setStart({actual_start_date:a.data.actual_start_date||a.data.expected_start_date||'',work_authorization_basis:a.data.work_authorization_basis||'',buddy_employee_id:a.data.buddy_employee_id||''});},[id]);
  useEffect(()=>{load();},[load]);
  const flash=m=>{setSaved(m);setTimeout(()=>setSaved(''),1600)};
  async function registerStart(){if(!start.actual_start_date||!start.work_authorization_basis.trim()){setErr('أدخل تاريخ المباشرة والأساس النظامي للعمل');return;}setBusy(true);const {error}=await supabase.rpc('register_candidate_start',{p_onboarding:id,p_start_date:start.actual_start_date,p_work_authorization_basis:start.work_authorization_basis,p_buddy_employee:start.buddy_employee_id||null});setBusy(false);if(error){setErr(error.message);return;}flash('تم تسجيل المباشرة الفعلية');load();}
  async function taskStatus(t,status){const {error}=await supabase.from('candidate_onboarding_tasks').update({status,completed_at:status==='done'?new Date().toISOString():null}).eq('id',t.id);if(error)setErr(error.message);else load();}
  async function assignTask(t,emp){const {error}=await supabase.from('candidate_onboarding_tasks').update({assigned_employee_id:emp||null}).eq('id',t.id);if(error)setErr(error.message);else load();}
  async function saveReview(r){const vals=['performance_score','attendance_score','behavior_score','technical_score'].map(k=>n(r[k])).filter(x=>x!=null);if(!vals.length){setErr('أدخل درجة واحدة على الأقل');return;}if(!r.recommendation){setErr('اختر توصية التقييم');return;}const {error}=await supabase.rpc('complete_probation_review',{p_review:r.id,p_reviewer:r.reviewer_employee_id||null,p_performance:n(r.performance_score),p_attendance:n(r.attendance_score),p_behavior:n(r.behavior_score),p_technical:n(r.technical_score),p_recommendation:r.recommendation,p_improvement_plan:r.improvement_plan||null,p_notes:r.notes||null});if(error){setErr(error.message);return;}flash('تم حفظ تقييم فترة التجربة');load();}
  if(!o)return <div className="empty">جارٍ تحميل ملف التهيئة…</div>;
  const c=o.candidates||{},jo=o.job_offers||{};
  const done=tasks.filter(t=>t.status==='done').length,total=tasks.length;
  return <><div className="page-head"><div><h1>{c.full_name_ar}</h1><p>{jo.job_title_snapshot||'—'} — {OSTATUS[o.status]||o.status}</p></div><div className="rowsplit"><Link className="btn ghost" href="/dashboard/recruitment/onboarding">التهيئة</Link><Link className="btn ghost" href={`/dashboard/recruitment/applications/${o.application_id}`}>ملف المرشح</Link></div></div>
  {err&&<div className="msg err" style={{marginBottom:12}}>{err}</div>}{saved&&<div className="msg ok" style={{marginBottom:12}}>{saved}</div>}
  <div className="grid k4" style={{marginBottom:16}}><div className="card"><h3>المباشرة المتوقعة</h3><div className="big" style={{fontSize:18}}>{dateAr(o.expected_start_date)}</div></div><div className="card"><h3>المباشرة الفعلية</h3><div className="big" style={{fontSize:18}}>{dateAr(o.actual_start_date)}</div></div><div className="card"><h3>نهاية فترة التجربة</h3><div className="big" style={{fontSize:18}}>{dateAr(o.probation_end_date)}</div></div><div className="card"><h3>مهام التهيئة</h3><div className="big">{done}/{total}</div></div></div>

  <div className="section" style={{marginTop:0,padding:18}}><header style={{margin:'-18px -18px 16px'}}><h2>تسجيل المباشرة</h2></header><div className="form-grid"><div className="field"><label>تاريخ المباشرة الفعلي *</label><input type="date" value={start.actual_start_date} onChange={e=>setStart({...start,actual_start_date:e.target.value})}/></div><div className="field span2"><label>الأساس النظامي للعمل *</label><input value={start.work_authorization_basis} onChange={e=>setStart({...start,work_authorization_basis:e.target.value})} placeholder="مثال: سعودي / نقل خدمات مكتمل / عقد أجير / تصريح نظامي آخر"/></div><div className="field"><label>الموظف المرافق</label><select value={start.buddy_employee_id} onChange={e=>setStart({...start,buddy_employee_id:e.target.value})}><option value="">يحدد لاحقاً</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name_ar}{e.department?` — ${e.department}`:''}</option>)}</select></div></div><button className="btn" style={{marginTop:12}} disabled={busy} onClick={registerStart}>{busy?'جارٍ التسجيل…':o.actual_start_date?'تحديث بيانات المباشرة':'تسجيل المباشرة الفعلية'}</button></div>

  <div className="section"><header><h2>خطة التهيئة</h2><span>{done} من {total} مكتمل</span></header><div style={{overflowX:'auto'}}><table><thead><tr><th>المهمة</th><th>الموعد</th><th>المسؤول</th><th>الحالة</th><th>—</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td style={{fontWeight:600}}>{t.task_name}</td><td>{dateAr(t.due_date)}</td><td><select value={t.assigned_employee_id||''} onChange={e=>assignTask(t,e.target.value)}><option value="">غير معين</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name_ar}</option>)}</select></td><td>{t.status==='pending'?'معلّق':t.status==='done'?'مكتمل':t.status==='skipped'?'متجاوز':t.status}</td><td className="rowsplit">{t.status!=='done'&&<button className="btn ghost" style={{padding:'3px 8px',fontSize:12}} onClick={()=>taskStatus(t,'done')}>تم</button>}{t.status==='done'&&<button className="btn ghost" style={{padding:'3px 8px',fontSize:12}} onClick={()=>taskStatus(t,'pending')}>إعادة فتح</button>}</td></tr>)}</tbody></table></div></div>

  <div className="section"><header><h2>تقييمات فترة التجربة</h2><span>كل 30 يوماً</span></header><div style={{padding:16}}>{reviews.map((r,idx)=><div key={r.id} style={{borderBottom:idx<reviews.length-1?'1px solid var(--hair)':'none',padding:'12px 0'}}><div className="rowsplit" style={{marginBottom:10}}><strong>تقييم اليوم {r.review_day}</strong><span style={{fontSize:12.5,color:'var(--ink-soft)'}}>موعده {dateAr(r.scheduled_date)} {r.status==='completed'&&`— النتيجة ${r.overall_score}/100`}</span></div><div className="form-grid"><div className="field"><label>المقيّم</label><select disabled={r.status==='completed'} value={r.reviewer_employee_id||''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,reviewer_employee_id:e.target.value}:x))}><option value="">اختر…</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name_ar}</option>)}</select></div><div className="field"><label>الأداء /100</label><input disabled={r.status==='completed'} type="number" min="0" max="100" value={r.performance_score??''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,performance_score:e.target.value}:x))}/></div><div className="field"><label>الانضباط والحضور /100</label><input disabled={r.status==='completed'} type="number" min="0" max="100" value={r.attendance_score??''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,attendance_score:e.target.value}:x))}/></div><div className="field"><label>السلوك والتعامل /100</label><input disabled={r.status==='completed'} type="number" min="0" max="100" value={r.behavior_score??''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,behavior_score:e.target.value}:x))}/></div><div className="field"><label>الكفاءة الفنية /100</label><input disabled={r.status==='completed'} type="number" min="0" max="100" value={r.technical_score??''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,technical_score:e.target.value}:x))}/></div><div className="field span2"><label>التوصية</label><select disabled={r.status==='completed'} value={r.recommendation||''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,recommendation:e.target.value}:x))}><option value="">اختر…</option>{Object.entries(RREC).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></div><div className="field span2"><label>خطة التحسين إن وجدت</label><input disabled={r.status==='completed'} value={r.improvement_plan||''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,improvement_plan:e.target.value}:x))}/></div><div className="field span3"><label>ملاحظات</label><textarea disabled={r.status==='completed'} rows="2" value={r.notes||''} onChange={e=>setReviews(reviews.map(x=>x.id===r.id?{...x,notes:e.target.value}:x))}/></div></div>{r.status!=='completed'&&<button className="btn" style={{marginTop:10}} onClick={()=>saveReview(r)}>حفظ التقييم والتوصية</button>}</div>)}{!reviews.length&&<div className="empty">ستنشأ تقييمات 30/60/90 يومًا تلقائياً بعد تسجيل المباشرة.</div>}</div></div>
  </>;
}
