create sequence if not exists public.transaction_register_no_seq start with 1 increment by 1;

create table if not exists public.transaction_register (
  id uuid primary key default gen_random_uuid(),
  transaction_no text not null unique default ('ARK-TX-' || lpad(nextval('public.transaction_register_no_seq')::text, 9, '0')),
  transaction_key text not null references public.transaction_definitions(transaction_key) on update cascade on delete restrict,
  source_table text not null,
  source_id uuid not null,
  source_destination_key text references public.procedure_destinations(destination_key) on update cascade on delete set null,
  origin_user_id uuid references public.app_users(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  current_destination_key text references public.procedure_destinations(destination_key) on update cascade on delete set null,
  current_user_id uuid references public.app_users(id) on delete set null,
  lifecycle_status text not null default 'open',
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  last_movement_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transaction_register_source_uq unique(transaction_key,source_table,source_id),
  constraint transaction_register_lifecycle_ck check (lifecycle_status in ('open','waiting','completed','closed','cancelled'))
);

create table if not exists public.transaction_movements (
  id uuid primary key default gen_random_uuid(),
  movement_seq bigint generated by default as identity unique,
  transaction_id uuid not null references public.transaction_register(id) on delete restrict,
  movement_kind text not null,
  from_destination_key text references public.procedure_destinations(destination_key) on update cascade on delete set null,
  to_destination_key text references public.procedure_destinations(destination_key) on update cascade on delete set null,
  actor_destination_key text references public.procedure_destinations(destination_key) on update cascade on delete set null,
  decision_destination_key text references public.procedure_destinations(destination_key) on update cascade on delete set null,
  actor_user_id uuid references public.app_users(id) on delete set null,
  target_user_id uuid references public.app_users(id) on delete set null,
  decision_key text,
  note text,
  source_engine text not null default 'system',
  source_engine_ref text,
  source_event_ref text unique,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_transaction_register_current on public.transaction_register(current_destination_key,lifecycle_status,last_movement_at desc);
create index if not exists idx_transaction_register_source on public.transaction_register(source_table,source_id);
create index if not exists idx_transaction_register_origin on public.transaction_register(origin_user_id,opened_at desc);
create index if not exists idx_transaction_movements_tx on public.transaction_movements(transaction_id,movement_seq);
create index if not exists idx_transaction_movements_actor on public.transaction_movements(actor_user_id,created_at desc);
create index if not exists idx_transaction_movements_target on public.transaction_movements(target_user_id,created_at desc);

alter table public.transaction_register enable row level security;
alter table public.transaction_movements enable row level security;
revoke all on public.transaction_register from public,anon,authenticated;
revoke all on public.transaction_movements from public,anon,authenticated;
revoke all on sequence public.transaction_register_no_seq from public,anon,authenticated;

insert into public.transaction_definitions(
  transaction_key,label_ar,module_key,resource_key,description_ar,
  has_temporal_effect,has_financial_effect,has_legal_effect,has_printable_output,is_periodic_or_aggregate,
  route_template,default_movement_kind,allow_request,allow_approval,allow_assignment,allow_inquiry,general_scope,is_active,requires_action
)
values(
  'work_communication','طلب / توجيه / تكليف عمل','system','my_work','تواصل عمل مستقل أو تكليف لا يرتبط بسجل مصدر آخر.',
  true,false,false,false,false,'none','choose',true,false,true,true,'both',true,false
)
on conflict (transaction_key) do nothing;

create or replace function private.fn_transaction_destination_from_module(p_module text)
returns text language sql stable set search_path=public,private,pg_temp as $$
  select case
    when p_module='hr' then 'workforce'
    when exists(select 1 from public.procedure_destinations d where d.destination_key=p_module and d.is_active) then p_module
    else null end;
$$;

create or replace function private.fn_transaction_key_from_approval(p_source_table text,p_transaction_type text)
returns text language plpgsql stable set search_path=public,private,pg_temp as $$
declare v_key text;
begin
  v_key:=private.fn_transaction_key_for_source(p_source_table);
  if v_key is not null then return v_key; end if;
  v_key:=case p_transaction_type when 'quotation_review' then 'quotation' when 'timesheet_week' then 'project_timesheet' else p_transaction_type end;
  if exists(select 1 from public.transaction_definitions where transaction_key=v_key and is_active) then return v_key; end if;
  return null;
end;
$$;

create or replace function private.fn_transaction_register_ensure(
  p_transaction_key text,p_source_table text,p_source_id uuid,p_source_destination_key text default null,
  p_origin_user_id uuid default null,p_project_id uuid default null,p_metadata jsonb default '{}'::jsonb
)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_id uuid;
begin
  if p_transaction_key is null or p_source_table is null or p_source_id is null then return null; end if;
  if not exists(select 1 from public.transaction_definitions where transaction_key=p_transaction_key and is_active) then return null; end if;
  if p_source_destination_key is not null and not exists(select 1 from public.procedure_destinations where destination_key=p_source_destination_key and is_active) then p_source_destination_key:=null; end if;
  insert into public.transaction_register(transaction_key,source_table,source_id,source_destination_key,origin_user_id,project_id,current_destination_key,metadata)
  values(p_transaction_key,p_source_table,p_source_id,p_source_destination_key,p_origin_user_id,p_project_id,p_source_destination_key,coalesce(p_metadata,'{}'::jsonb))
  on conflict (transaction_key,source_table,source_id) do update
  set source_destination_key=coalesce(public.transaction_register.source_destination_key,excluded.source_destination_key),
      origin_user_id=coalesce(public.transaction_register.origin_user_id,excluded.origin_user_id),
      project_id=coalesce(public.transaction_register.project_id,excluded.project_id),
      current_destination_key=coalesce(public.transaction_register.current_destination_key,excluded.current_destination_key),
      metadata=public.transaction_register.metadata||excluded.metadata,
      updated_at=now()
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function private.fn_transaction_register_move(
  p_transaction_id uuid,p_movement_kind text,p_actor_user_id uuid default null,p_from_destination_key text default null,
  p_to_destination_key text default null,p_target_user_id uuid default null,p_actor_destination_key text default null,
  p_decision_destination_key text default null,p_decision_key text default null,p_note text default null,
  p_source_engine text default 'system',p_source_engine_ref text default null,p_source_event_ref text default null,
  p_payload jsonb default '{}'::jsonb,p_lifecycle_status text default null
)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_tx public.transaction_register%rowtype; v_id uuid; v_from text; v_now timestamptz:=now();
begin
  if p_transaction_id is null or nullif(trim(coalesce(p_movement_kind,'')),'') is null then return null; end if;
  if p_source_event_ref is not null then
    select id into v_id from public.transaction_movements where source_event_ref=p_source_event_ref;
    if v_id is not null then return v_id; end if;
  end if;
  select * into v_tx from public.transaction_register where id=p_transaction_id for update;
  if not found then return null; end if;
  v_from:=coalesce(p_from_destination_key,v_tx.current_destination_key,v_tx.source_destination_key);
  insert into public.transaction_movements(transaction_id,movement_kind,from_destination_key,to_destination_key,actor_destination_key,decision_destination_key,actor_user_id,target_user_id,decision_key,note,source_engine,source_engine_ref,source_event_ref,payload,created_at)
  values(p_transaction_id,p_movement_kind,v_from,p_to_destination_key,coalesce(p_actor_destination_key,v_from),p_decision_destination_key,p_actor_user_id,p_target_user_id,p_decision_key,p_note,coalesce(nullif(p_source_engine,''),'system'),p_source_engine_ref,p_source_event_ref,coalesce(p_payload,'{}'::jsonb),v_now)
  returning id into v_id;
  update public.transaction_register
  set current_destination_key=coalesce(p_to_destination_key,current_destination_key),
      current_user_id=case when p_lifecycle_status in ('closed','cancelled') then null when p_to_destination_key is not null then p_target_user_id else current_user_id end,
      lifecycle_status=coalesce(p_lifecycle_status,lifecycle_status),
      closed_at=case when p_lifecycle_status in ('closed','cancelled') then coalesce(closed_at,v_now) else closed_at end,
      last_movement_at=v_now,updated_at=v_now
  where id=p_transaction_id;
  return v_id;
end;
$$;

create or replace function private.fn_transaction_id_for_approval(p_workflow public.approval_workflows)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_key text; v_source_dest text;
begin
  v_key:=private.fn_transaction_key_from_approval(p_workflow.source_table,p_workflow.transaction_type);
  if v_key is null then return null; end if;
  v_source_dest:=private.fn_transaction_destination_from_module(p_workflow.source_module);
  return private.fn_transaction_register_ensure(v_key,p_workflow.source_table,p_workflow.source_id,v_source_dest,p_workflow.origin_user_id,p_workflow.project_id,
    jsonb_build_object('source_label',p_workflow.source_label,'amount',p_workflow.amount,'currency',p_workflow.currency,'approval_workflow_no',p_workflow.workflow_no));
end;
$$;

create or replace function private.trg_transaction_register_approval_workflow()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_tx uuid; v_source_dest text; v_lifecycle text; v_to text;
begin
  v_tx:=private.fn_transaction_id_for_approval(new); if v_tx is null then return new; end if;
  v_source_dest:=private.fn_transaction_destination_from_module(new.source_module);
  if tg_op='INSERT' then
    perform private.fn_transaction_register_move(v_tx,'approval_submitted',new.origin_user_id,v_source_dest,null,null,v_source_dest,null,null,null,'approval',new.id::text,'approval_workflow:'||new.id::text||':submitted',jsonb_build_object('workflow_no',new.workflow_no,'status',new.status));
  elsif new.status is distinct from old.status then
    v_lifecycle:=case when new.status in ('approved','rejected','cancelled') then case when new.status='cancelled' then 'cancelled' else 'closed' end else 'open' end;
    v_to:=case when new.status='returned' then v_source_dest else null end;
    perform private.fn_transaction_register_move(v_tx,'approval_status',null,null,v_to,null,null,case when new.status='returned' then v_source_dest else null end,new.status,new.return_note,'approval',new.id::text,'approval_workflow:'||new.id::text||':status:'||new.status||':'||new.version_no::text,jsonb_build_object('workflow_no',new.workflow_no,'status',new.status),v_lifecycle);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_transaction_register_approval_workflow on public.approval_workflows;
create trigger trg_transaction_register_approval_workflow after insert or update of status on public.approval_workflows for each row execute function private.trg_transaction_register_approval_workflow();

create or replace function private.trg_transaction_register_approval_step()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_w public.approval_workflows%rowtype; v_tx uuid; v_source_dest text; v_to text; v_event text;
begin
  select * into v_w from public.approval_workflows where id=new.workflow_id; if not found then return new; end if;
  v_tx:=private.fn_transaction_id_for_approval(v_w); if v_tx is null then return new; end if;
  v_source_dest:=private.fn_transaction_destination_from_module(v_w.source_module);
  if tg_op='INSERT' then
    perform private.fn_transaction_register_move(v_tx,'approval_route',new.requested_by_user_id,null,new.target_portal_key,new.target_user_id,null,null,null,new.request_reason,'approval_step',new.id::text,'approval_step:'||new.id::text||':route',jsonb_build_object('step_order',new.step_order,'action_type',new.action_type,'target_group_key',new.target_group_key,'target_capability',new.target_capability,'is_blocking',new.is_blocking));
  elsif (new.acted_at is not null and old.acted_at is null) or new.status is distinct from old.status then
    v_to:=case when new.status='returned' then v_source_dest else null end;
    v_event:='approval_step:'||new.id::text||':decision:'||coalesce(new.status,'unknown')||':'||coalesce(extract(epoch from new.acted_at)::bigint::text,'0');
    perform private.fn_transaction_register_move(v_tx,'approval_decision',new.acted_by_user_id,null,v_to,null,new.target_portal_key,new.target_portal_key,new.status,new.decision_comment,'approval_step',new.id::text,v_event,jsonb_build_object('step_order',new.step_order,'action_type',new.action_type,'target_capability',new.target_capability));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_transaction_register_approval_step on public.approval_workflow_steps;
create trigger trg_transaction_register_approval_step after insert or update of status,acted_at on public.approval_workflow_steps for each row execute function private.trg_transaction_register_approval_step();

create or replace function private.fn_transaction_id_for_workspace_task(p_task public.workspace_tasks)
returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_w public.approval_workflows%rowtype; v_key text;
begin
  if p_task.approval_workflow_id is not null then
    select * into v_w from public.approval_workflows where id=p_task.approval_workflow_id;
    if found then return private.fn_transaction_id_for_approval(v_w); end if;
  end if;
  if p_task.source_table is not null and p_task.source_id is not null then
    v_key:=private.fn_transaction_key_for_source(p_task.source_table);
    if v_key is not null then
      return private.fn_transaction_register_ensure(v_key,p_task.source_table,p_task.source_id,coalesce(p_task.source_portal_key,p_task.portal_key),p_task.creator_user_id,p_task.project_id,jsonb_build_object('source_label',p_task.source_label,'task_title',p_task.title));
    end if;
  end if;
  return private.fn_transaction_register_ensure('work_communication','workspace_tasks',p_task.id,coalesce(p_task.source_portal_key,p_task.portal_key),p_task.creator_user_id,p_task.project_id,jsonb_build_object('task_title',p_task.title,'task_type',p_task.task_type));
end;
$$;

create or replace function private.trg_transaction_register_workspace_task()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_tx uuid; v_from text; v_to text; v_kind text;
begin
  v_tx:=private.fn_transaction_id_for_workspace_task(new); if v_tx is null then return new; end if;
  v_from:=coalesce(new.source_portal_key,new.portal_key); v_to:=coalesce(new.target_portal_key,new.current_destination_key,v_from);
  v_kind:=case when new.communication_kind='inquiry' then 'inquiry' when new.task_type='request' then 'request' else 'assignment' end;
  perform private.fn_transaction_register_move(v_tx,v_kind,new.creator_user_id,v_from,v_to,new.assignee_user_id,v_from,null,null,new.description,'workspace_task',new.id::text,'workspace_task:'||new.id::text||':created',jsonb_build_object('title',new.title,'priority',new.priority,'task_type',new.task_type,'communication_kind',new.communication_kind,'source_label',new.source_label));
  return new;
end;
$$;

drop trigger if exists trg_transaction_register_workspace_task on public.workspace_tasks;
create trigger trg_transaction_register_workspace_task after insert on public.workspace_tasks for each row execute function private.trg_transaction_register_workspace_task();

create or replace function private.trg_transaction_register_workspace_event()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_task public.workspace_tasks%rowtype; v_tx uuid; v_lifecycle text;
begin
  select * into v_task from public.workspace_tasks where id=new.task_id; if not found then return new; end if;
  v_tx:=private.fn_transaction_id_for_workspace_task(v_task); if v_tx is null then return new; end if;
  v_lifecycle:=case when new.event_type in ('closed','cancelled') then case when new.event_type='cancelled' then 'cancelled' else 'closed' end when new.event_type='completed' then 'completed' else null end;
  perform private.fn_transaction_register_move(v_tx,'work_'||new.event_type,new.actor_user_id,null,coalesce(v_task.current_destination_key,v_task.target_portal_key),new.subject_user_id,null,null,new.to_status,new.note,'workspace_event',new.id::text,'workspace_event:'||new.id::text,jsonb_build_object('from_status',new.from_status,'to_status',new.to_status,'progress',new.progress,'document_id',new.document_id),v_lifecycle);
  return new;
end;
$$;

drop trigger if exists trg_transaction_register_workspace_event on public.workspace_task_events;
create trigger trg_transaction_register_workspace_event after insert on public.workspace_task_events for each row execute function private.trg_transaction_register_workspace_event();

create or replace function private.trg_transaction_register_action_envelope()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_def public.transaction_definitions%rowtype; v_tx uuid; v_source_dest text;
begin
  select * into v_def from public.transaction_definitions where transaction_key=new.transaction_key; if not found then return new; end if;
  v_source_dest:=coalesce(new.source_destination_key,private.fn_transaction_destination_from_module(v_def.module_key));
  v_tx:=private.fn_transaction_register_ensure(new.transaction_key,new.source_table,new.source_id,v_source_dest,new.origin_user_id,null,jsonb_build_object('constitution_snapshot',new.constitution_snapshot));
  if tg_op='INSERT' then
    perform private.fn_transaction_register_move(v_tx,'action_required',new.origin_user_id,v_source_dest,null,null,v_source_dest,null,null,new.note,'constitution_hook',new.id::text,'action_envelope:'||new.id::text||':created',jsonb_build_object('action_kind',new.action_kind,'status',new.status));
  else
    if new.completed_input_at is not null and old.completed_input_at is null then
      perform private.fn_transaction_register_move(v_tx,'action_prepared',new.origin_user_id,v_source_dest,new.target_destination_key,new.target_user_id,v_source_dest,null,null,new.note,'constitution_hook',new.id::text,'action_envelope:'||new.id::text||':prepared',jsonb_build_object('action_kind',new.action_kind,'status',new.status));
    end if;
    if new.dispatched_at is not null and old.dispatched_at is null then
      perform private.fn_transaction_register_move(v_tx,'action_dispatched',new.origin_user_id,null,new.target_destination_key,new.target_user_id,null,null,null,new.note,'constitution_hook',new.id::text,'action_envelope:'||new.id::text||':dispatched',jsonb_build_object('action_kind',new.action_kind,'status',new.status));
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_transaction_register_action_envelope on public.transaction_action_envelopes;
create trigger trg_transaction_register_action_envelope after insert or update of completed_input_at,dispatched_at on public.transaction_action_envelopes for each row execute function private.trg_transaction_register_action_envelope();

create or replace function public.fn_transaction_journey(p_transaction_id uuid default null,p_transaction_no text default null,p_source_table text default null,p_source_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$
declare v_tx public.transaction_register%rowtype; v_uid uuid:=auth.uid(); v_allowed boolean:=false; v_moves jsonb;
begin
  if v_uid is null then raise exception 'يجب تسجيل الدخول'; end if;
  select * into v_tx from public.transaction_register t
  where (p_transaction_id is not null and t.id=p_transaction_id)
     or (p_transaction_no is not null and t.transaction_no=p_transaction_no)
     or (p_source_table is not null and p_source_id is not null and t.source_table=p_source_table and t.source_id=p_source_id)
  order by case when p_transaction_id is not null and t.id=p_transaction_id then 1 when p_transaction_no is not null and t.transaction_no=p_transaction_no then 2 else 3 end limit 1;
  if not found then return null; end if;
  v_allowed:=public.fn_is_primary_user() or v_tx.origin_user_id=v_uid or v_tx.current_user_id=v_uid
    or exists(select 1 from public.transaction_movements m where m.transaction_id=v_tx.id and (m.actor_user_id=v_uid or m.target_user_id=v_uid))
    or exists(select 1 from public.transaction_movements m join public.v_my_capabilities c on c.capability_key=(m.payload->>'target_capability') where m.transaction_id=v_tx.id and nullif(m.payload->>'target_capability','') is not null);
  if not v_allowed then raise exception 'لا تملك صلاحية عرض مسار هذه المعاملة'; end if;
  select coalesce(jsonb_agg(to_jsonb(m) order by m.movement_seq),'[]'::jsonb) into v_moves from public.transaction_movements m where m.transaction_id=v_tx.id;
  return jsonb_build_object('transaction',to_jsonb(v_tx),'movements',v_moves);
end;
$$;
revoke all on function public.fn_transaction_journey(uuid,text,text,uuid) from public,anon;
grant execute on function public.fn_transaction_journey(uuid,text,text,uuid) to authenticated;

-- Backfill existing approval history without changing its business state.
do $$
declare w public.approval_workflows%rowtype; s public.approval_workflow_steps%rowtype; tx uuid; src text; life text;
begin
  for w in select * from public.approval_workflows order by created_at loop
    tx:=private.fn_transaction_id_for_approval(w); if tx is null then continue; end if;
    src:=private.fn_transaction_destination_from_module(w.source_module);
    perform private.fn_transaction_register_move(tx,'approval_submitted',w.origin_user_id,src,null,null,src,null,null,null,'approval',w.id::text,'approval_workflow:'||w.id::text||':submitted',jsonb_build_object('workflow_no',w.workflow_no,'status',w.status,'backfilled',true));
    for s in select * from public.approval_workflow_steps where workflow_id=w.id order by version_no,step_order,created_at loop
      perform private.fn_transaction_register_move(tx,'approval_route',s.requested_by_user_id,null,s.target_portal_key,s.target_user_id,null,null,null,s.request_reason,'approval_step',s.id::text,'approval_step:'||s.id::text||':route',jsonb_build_object('step_order',s.step_order,'action_type',s.action_type,'target_group_key',s.target_group_key,'target_capability',s.target_capability,'backfilled',true));
      if s.acted_at is not null then
        perform private.fn_transaction_register_move(tx,'approval_decision',s.acted_by_user_id,null,case when s.status='returned' then src else null end,null,s.target_portal_key,s.target_portal_key,s.status,s.decision_comment,'approval_step',s.id::text,'approval_step:'||s.id::text||':decision:'||coalesce(s.status,'unknown')||':'||coalesce(extract(epoch from s.acted_at)::bigint::text,'0'),jsonb_build_object('step_order',s.step_order,'action_type',s.action_type,'target_capability',s.target_capability,'backfilled',true));
      end if;
    end loop;
    if w.status<>'pending' then
      life:=case when w.status in ('approved','rejected') then 'closed' when w.status='cancelled' then 'cancelled' else 'open' end;
      perform private.fn_transaction_register_move(tx,'approval_status',null,null,case when w.status='returned' then src else null end,null,null,case when w.status='returned' then src else null end,w.status,w.return_note,'approval',w.id::text,'approval_workflow:'||w.id::text||':status:'||w.status||':'||w.version_no::text,jsonb_build_object('workflow_no',w.workflow_no,'status',w.status,'backfilled',true),life);
    end if;
  end loop;
end $$;

-- Backfill existing work items and their event history.
do $$
declare t public.workspace_tasks%rowtype; e public.workspace_task_events%rowtype; tx uuid; src text; dest text; kind text; life text;
begin
  for t in select * from public.workspace_tasks order by created_at loop
    tx:=private.fn_transaction_id_for_workspace_task(t); if tx is null then continue; end if;
    src:=coalesce(t.source_portal_key,t.portal_key); dest:=coalesce(t.target_portal_key,t.current_destination_key,src);
    kind:=case when t.communication_kind='inquiry' then 'inquiry' when t.task_type='request' then 'request' else 'assignment' end;
    perform private.fn_transaction_register_move(tx,kind,t.creator_user_id,src,dest,t.assignee_user_id,src,null,null,t.description,'workspace_task',t.id::text,'workspace_task:'||t.id::text||':created',jsonb_build_object('title',t.title,'priority',t.priority,'task_type',t.task_type,'communication_kind',t.communication_kind,'backfilled',true));
    for e in select * from public.workspace_task_events where task_id=t.id order by created_at,id loop
      life:=case when e.event_type='closed' then 'closed' when e.event_type='cancelled' then 'cancelled' when e.event_type='completed' then 'completed' else null end;
      perform private.fn_transaction_register_move(tx,'work_'||e.event_type,e.actor_user_id,null,coalesce(t.current_destination_key,t.target_portal_key),e.subject_user_id,null,null,e.to_status,e.note,'workspace_event',e.id::text,'workspace_event:'||e.id::text,jsonb_build_object('from_status',e.from_status,'to_status',e.to_status,'progress',e.progress,'document_id',e.document_id,'backfilled',true),life);
    end loop;
  end loop;
end $$;
