name: Probe runner
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/_probe.yml
jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Probe
        run: echo ok
